risinglightdb/sqllogictest-rs

.github/workflows/ci.yml, examples/basic.rs, examples/basic.slt, examples/rowsort.rs, examples/rowsort.slt, examples/test_dir_escape.rs, examples/test_dir_escape.slt
close https://github.com/singularity-data/sqllogictest-rs/issues/1
=> docs: add examples

README.md, src/lib.rs
This PR improves the documentation in README and rustdoc.
close https://github.com/singularity-data/sqllogictest-rs/issues/6
=> docs: add usage to README

src/parser.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
=> parser: Logic cleanup around sql result check

.gitignore, Cargo.toml, examples/basic.rs, examples/include.rs, examples/rowsort.rs, examples/test_dir_escape.rs, examples/validator.rs, src/main.rs, src/runner.rs
finish remaining works of https://github.com/singularity-data/sqllogictest-rs/pull/2
=> feat: migrate runner to async db

.github/workflows/release.yml
=> ci: fix workflow

CHANGELOG.md, Cargo.toml, README.md, src/runner.rs
=> docs: update change log and bump 0.3

.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, CHANGELOG.md, Cargo.toml, examples/file_level_sort_mode.rs, examples/rowsort.rs, rustfmt.toml, src/main.rs, src/parser.rs, src/runner.rs
close https://github.com/risinglightdb/sqllogictest-rs/issues/19
=> feat: new test ui

Cargo.toml, src/main.rs
=> fix: return code should be non-zero if test case failed

CHANGELOG.md, Cargo.toml, src/main.rs
=> feat: add --color arg for cli

CHANGELOG.md, README.md, src/main.rs
close https://github.com/risinglightdb/sqllogictest-rs/issues/37
=> feat: panic when no test case is found

Cargo.toml, examples/include/a.slt, examples/include/b.slt, examples/include_1.slt, src/lib.rs, src/parser.rs
=> feat: Add wildchar support for include

Cargo.toml, src/main.rs
close https://github.com/risinglightdb/sqllogictest-rs/issues/41
=> feat(ui): show diff instead of actual / expected data in cli mode

CHANGELOG.md, Cargo.toml, README.md
=> release: bump to v0.5.2

Cargo.toml, src/main.rs
Otherwise some services won't recognize this unit file 🤣
=> chore: add timestamp to junit

src/main.rs
=> fix: panic without junit

CHANGELOG.md, Cargo.toml
=> release: bump to v0.5.5

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/bin/sqllogictest.rs, sqllogictest-bin/src/engines/mod.rs, sqllogictest-bin/src/lib.rs, sqllogictest/Cargo.toml, sqllogictest/src/lib.rs
* update changelog
* fix default value of engine
* rename sqllogictest-bin/main.rs -> sqllogictest-bin/bin/sqllogictest.rs so that the installed crate has the same name as before.
=> fix(bin): unsupported engine postgresql

README.md, sqllogictest-bin/Cargo.toml, sqllogictest-bin/README.md, sqllogictest/README.md
0.6.0 has been released. This commit adds the changes for successfully publishing the release.
=> fix(release): add readme

README.md, examples/basic/Cargo.toml, examples/condition/Cargo.toml, examples/file_level_sort_mode/Cargo.toml, examples/include/Cargo.toml, examples/rowsort/Cargo.toml, examples/test_dir_escape/Cargo.toml, examples/validator/Cargo.toml
=> fix(release): forbid publish examples

CHANGELOG.md, sqllogictest-bin/Cargo.toml, sqllogictest/Cargo.toml, sqllogictest/src/runner.rs
=> release: bump to v0.6.1

sqllogictest-bin/src/engines/mod.rs, sqllogictest-bin/src/lib.rs
=> refactor: use enum for engine type

CHANGELOG.md, sqllogictest/Cargo.toml, sqllogictest/src/runner.rs
Also move hook functions to a new async-trait to avoid struggling with lifetime.
=> release: v0.6.3

sqllogictest-bin/src/lib.rs
close https://github.com/risinglightdb/sqllogictest-rs/issues/85
=> feat: use one session for each file in serial mode

CHANGELOG.md, sqllogictest-bin/Cargo.toml, sqllogictest/Cargo.toml
Signed-off-by: xxchan <xxchan22f@gmail.com>
=> release: bump to v0.6.4

sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
This PR makes `Location` hierarchical to represent a full stack of included files.
This will make it easier to locate errors in parallel tests.
An example:
```
statement failed: db error: ERROR: QueryError: sql parser error: Expected an SQL statement, found: TABLE
[SQL] ...
at e2e_test/batch/../tpch/create_tables.slt.part:1
at e2e_test/batch/tpch.slt:7
```
=> feat: print file stack on error

sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/engines/external.rs, sqllogictest-bin/src/engines/mod.rs, sqllogictest-bin/src/lib.rs, sqllogictest/src/runner.rs
Signed-off-by: TennyZhuang <zty0826@gmail.com>
I will also create a jdbc driver repo.
=> feat: support external driver by subprocess

CHANGELOG.md, Cargo.toml, sqllogictest-bin/Cargo.toml
Signed-off-by: TennyZhuang <zty0826@gmail.com>
=> release: bump to v0.7.0

README.md
Signed-off-by: xudong963 <wxd963996380@gmail.com>
=> Add databend as user

sqllogictest/src/runner.rs
Since the log seems unintentional, might as well...
Resolves #158
=> chore: downgrade logging in sqllogictest crate to debug

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: bump to v0.11.2

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-engines/Cargo.toml
=> release: bump to v0.12.0

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: bump to v0.12.1

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/engines.rs, sqllogictest-bin/src/lib.rs
Usage:
```sh
sqllogictest --options="xxx" ...
```
=> feat: support pgoptions

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest/src/runner.rs
close https://github.com/risinglightdb/sqllogictest-rs/issues/213
Signed-off-by: xxchan <xxchan22f@gmail.com>
=> add logs for system commands

.github/workflows/release.yml, sqllogictest/src/column_type.rs
broken by #226
failure run https://github.com/risinglightdb/sqllogictest-rs/actions/runs/9738772185/job/28031547976
=> ci: fix release workflow

CHANGELOG.md, Cargo.toml
I'll release once this gets merged.
=> version: bump to 0.22.1

.github/workflows/ci.yml, Cargo.lock, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs
Fix https://github.com/risinglightdb/sqllogictest-rs/pull/246#discussion_r1982829234.
=> fix(bin): fix incorrect "skipping" message

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest/src/runner.rs
Support test case partitioning in both runner and binary. The ideas behind:
- https://nexte.st/docs/ci-features/partitioning/
- https://buildkite.com/docs/pipelines/tutorials/parallel-builds#parallel-jobs
=> feat(runner, bin): support test case partitioning

README.md, sqllogictest-bin/src/main.rs
Signed-off-by: xxchan <xxchan22f@gmail.com>
=> doc: $__DATABASE__

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml
=> chore: bump version to v0.28.1

.github/workflows/ci.yml, Cargo.lock, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs, sqllogictest/src/substitution.rs
Changes:
- Add args to skip test files that match the regex.
- Bump cargo-semver-checks for CI.
=> feat: support skip files with regex

CHANGELOG.md, Cargo.lock, Cargo.toml
- release a new version to include the new enhencement 
really love the new changes ❤️
=> chore: bump version to v0.28.4
