examples/include.rs, examples/include_1.slt, examples/include_2.slt, src/lib.rs
Add support to include another slt file, which is very useful in data importing.
The syntax is not a part of standard sqllogictest, and we are not ready to stabilize it, so I mark it as hidden.
=> feat: support include statement

README.md
From a regulation perspective, DCO is not required for people inside this organization. But for other contributors, they should sign a DCO to certify that they wrote or otherwise have the right to submit the code they are contributing to the project.
=> docs: add DCO guide in contributing

CHANGELOG.md, Cargo.toml, README.md
We are going to publish the current version as v0.2.0.
=> chore: publish as v0.2.0

examples/validator.rs, examples/validator.slt, src/runner.rs
This PR is a PoC for #13 to get a quick preview of my idea.
Welcome any comments.
=> runner: Implement validator support

src/parser.rs
Currently the parser will replace all '\n' with ' ' in the input SQL, which makes it unreadable in error messages.
=> fix(parser): keep newline char in sql

examples/file_level_sort_mode.rs, examples/file_level_sort_mode.slt, src/parser.rs, src/runner.rs
As in #24 , we need a syntax to control the file-level sort mode.
This pr introduce syntax `control sortmode {sort_mode}` to do it.
=> feat: support file-level sort mode control syntax

examples/condition.rs, examples/condition.slt, src/main.rs, src/parser.rs, src/runner.rs
This PR add the support of evaluating `skipif` and `onlyif` conditions for the runner. 
[References.](https://github.com/gregrahn/sqllogictest/blob/2777692befa12f626c76c29e3111b68888ffbb06/src/sqllogictest.c#L467-L491
)
For binary, we can specify the engine name by a new command-line argument of `--engine`. The default value is `postgresql`.
=> feat: support evaluating `skipif` and `onlyif` conditions

CHANGELOG.md, Cargo.toml, src/main.rs
Signed-off-by: Noel Kwan <noelkwan1998@gmail.com>
Closes https://github.com/risinglightdb/sqllogictest-rs/issues/46.
Thanks to @skyzh for pointing out relevant lines of code :)
=> fix: render empty strings

src/parser.rs
Signed-off-by: Renjie Liu <liurenjie2008@gmail.com>
When `include` contains wildchar, the expaned include statement before:
```
./example/*.slt
./example/*.slt
```
After fixed:
```
./example/a.slt
./example/b.slt
```
=> Fix include file name

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/main.rs, src/parser.rs
junit is a generic exchange format of delivering test result. With this integration, sqllogictest users can upload and analyze sqllogictest result with ease.
Also bump a minor version as this doesn't change lib interface.
=> feat: add junit support

CHANGELOG.md, Cargo.toml, src/main.rs
The unit test case name might contain characters like `/`. We filter them out in this PR.
=> fix: junit test case name sanitizer

examples/basic.rs, examples/condition.rs, examples/file_level_sort_mode.rs, examples/rowsort.rs, examples/test_dir_escape.rs, examples/validator.rs, src/main.rs, src/runner.rs
This PR moves the diff output into the `TestErrorKind` struct.
=> refactor: move diff output into lib

src/runner.rs
This PR adds a function `sleep` to `AsyncDB` trait, so that we can specify how the runner does it.
By default it calls `std::thread::sleep` as previous. We can change it to `tokio::time::sleep` or `madsim::time::sleep` in necessary.
I'm not sure whether it should be a public API so I hide it from rustdoc.
=> feat: add sleep fn to AsyncDB

Cargo.toml, src/main.rs
Support extended query mode.
It's compatible with past versions, extended query mode only takes effect when using the flag  "--extend"
for now, this pr has the following limit:
- we only support most common type in binary format (but not all the type.
- rust-postgres only support one-dimensional array type.
Hence we can run all original e2e test now.
=> support extended query mode

sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
Previously, non-existent file will make parser panic & parser error will make runner panic. This PR improves both.
=> feat: improve error handling for parser & runner

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest/Cargo.toml
=> refactor: use cargo workspace inheritance

sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/engines/postgres_extended.rs, sqllogictest-bin/src/engines/postgres_extended_test.slt, sqllogictest/src/runner.rs
This PR does two things:
1. support INTERVAL && TIMESTAMPTZ type in postgres-extended 
2. refactor run() in postgres-extended: use a macro to generate process
=> support more type in postgres-extended

examples/basic/examples/basic.rs, examples/condition/examples/condition.rs, examples/file_level_sort_mode/examples/file_level_sort_mode.rs, examples/include/examples/include.rs, examples/rowsort/examples/rowsort.rs, examples/test_dir_escape/examples/test_dir_escape.rs, examples/validator/examples/validator.rs, sqllogictest-bin/src/engines/external.rs, sqllogictest-bin/src/engines/mod.rs, sqllogictest-bin/src/engines/postgres.rs, sqllogictest-bin/src/engines/postgres_extended.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs, tests/harness.rs, tests/slt/a.slt, tests/slt/b/b.slt
- Breaking change to `DB` trait
- fix https://github.com/risinglightdb/sqllogictest-rs/issues/107
- fix https://github.com/risinglightdb/sqllogictest-rs/issues/103
- https://github.com/risinglightdb/sqllogictest-rs/issues/36 is now possible, but I didn't enable it yet. I'd like to implement https://github.com/risinglightdb/sqllogictest-rs/issues/43 first so that we can update painlessly.
- Breaking change: only sort actual results now. We need to sort before compute hash. And sorting `Vec<Vec<String>>` is different from sorting rows `Vec<String>`. Note that because of this, risingwave cannot use this version yet.. So we quite need #43
=> refactor: use Vec<Vec<String>> as query results & fix hash-threshold  

sqllogictest-bin/src/engines/postgres.rs, sqllogictest-bin/src/engines/postgres_extended.rs, sqllogictest-bin/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
- add CLI option `--override`, and `--format`
- type string and column number not checked yet (https://github.com/risinglightdb/sqllogictest-rs/issues/36), but it would be easy. We need to update the engines first.
- breaking changes to `Record` and parser
- retain `Include` record when linking its content
- keep parsing after `Halt`
- move `Begin/EndInclude` to `Injected`
- breaking change: remove `Hook`
sample run: https://github.com/risingwavelabs/risingwave/pull/6776
close https://github.com/risinglightdb/sqllogictest-rs/issues/43
close https://github.com/risinglightdb/sqllogictest-rs/pull/90
=> feat: support generate & format test files

.github/workflows/release.yml, CHANGELOG.md, Cargo.toml, README.md, sqllogictest-bin/Cargo.toml
Also change release workflow to https://github.com/anton-yurchenko/git-release, which supports parsing Keep a Changelog format. (And the old one is actually deprecated)
=> release: bump to 0.9.0

.github/workflows/release.yml
Currently it's
Change according to the example https://github.com/anton-yurchenko/git-release/blob/main/docs/example.md#release-title-with-prefix
=> ci: tweak release name

README.md
This is an awesome library -- it has already saved me huge amounts of time on DataFusion. Thank you so much @xxchan . I wanted to contribute back
This first proposed addition adds some examples to the README to try and help users get started even faster (as well as make some of the features like error string matching) more discoverable. 
Let me know what you think,
=> Add a quick start cookbook to the README

sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
First of all, thank you again for this library -- it is really awesome. 
I am trying to implement "test script completion mode" in DataFusion. In order to do so, I would like to be able to update parsed `Records` with new output and then write them back to a file. Ideally the only changes in the file would be the new results and the original file will have all the comments, whitespace, etc. 
DataFusion ticket: https://github.com/apache/arrow-datafusion/issues/4570, https://github.com/apache/arrow-datafusion/issues/4570#issuecomment-1345252492
1. Add `impl Display` for Record (refactor `unparse`)
2. Add tests for roundtrip parsing / unparsing
3. Add `Record::Whitespace` so the whitespace in the original files can be reconstructed (found during testing)
1. I had a question about whitespace …
=> Improve the ability to parse/unparse files

sqllogictest-bin/src/lib.rs
#127 introduced `Record::Newline`. We don't need to insert newlines between records, and we can preserve newlines.
=> fix(bin): fix newline handling for `--format/override`

sqllogictest/Cargo.toml, sqllogictest/src/parser.rs
Follow on to https://github.com/risinglightdb/sqllogictest-rs/pull/127
Here is a proposed method for testing that parsing the results of `unparsing` are the same records.
=> Test for parse(unparse(parse()) is identity

sqllogictest/src/runner.rs
See https://github.com/risinglightdb/sqllogictest-rs/issues/13#issuecomment-1345263034 for some contexts
For actual results, we can keep `Vec<Vec<String>` which can give more chances for users to define their `Validator`.
=> Change the type for Validator

sqllogictest-bin/src/lib.rs, sqllogictest/src/runner.rs
~Draft as it builds on https://github.com/risinglightdb/sqllogictest-rs/pull/129~
I want to be able to update Records given the output of a particular run (see https://github.com/apache/arrow-datafusion/issues/4570)
1. Add `update_record_with_output` function 
2. Tests
I think this is my last planned PR to `sqllogictest` for a bit (I want to go try and integrated this into DataFusion upstream first)
=> Add `update_record_with_output` function and tests 

sqllogictest/src/runner.rs
Fixes a small  typo in `QueryResultMismatch` display.
=> fix: Correct typo in `QueryResultMismatch` display

sqllogictest-bin/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
Signed-off-by: xudong963 <wxd963996380@gmail.com>
It's better to make `update_test_file` not have ownership of `runner`.
=> Make `update_test_file` not have ownership of runner

sqllogictest/src/runner.rs
If the engine returns a value with leading spaces, it will affect the result of rowsort, but won't be recognized in error message since we trim the string before reporting error but after the rowsort. This PR trims the string before rowsort to avoid this problem. Despite this, engines should not return a value with leading or tailing space.
=> fix: trim string before rowsort

sqllogictest-bin/src/engines/external.rs, sqllogictest/src/runner.rs
- jdbc side: https://github.com/risinglightdb/sqllogictest-driver-jdbc/pull/6
- Also Revert "trim string before rowsort (#137)" acoording to the comments in the PR
=> fix: use Vec<Vec<String>> for external engine

sqllogictest/src/parser.rs
Should fix https://github.com/apache/arrow-datafusion/issues/4494
Currently when parsing files which use `\r\n` to separate lines on Windows, the query-result separator line looks like `----\r`. This fails the `if line == "----" {` check, resulting in the whole file being swallowed as part of the query. The built-in `lines` method fixes this issue by splitting on both `\n` and `\r\n`. 
The change in the result for the `include_glob` test is due to `lines()` trimming a trailing newline from one of the included files.
=> Use lines() instead of split('\n') in parse_inner

sqllogictest-bin/src/engines/postgres.rs, sqllogictest-bin/src/engines/postgres_extended.rs, sqllogictest/src/runner.rs
Resolve issue #140
Fix a typo
Local test has passed:
=> fix: parse dml with ```returning``` as a query

examples/condition/examples/condition.rs, examples/file_level_sort_mode/examples/file_level_sort_mode.rs, examples/include/examples/include.rs, examples/rowsort/examples/rowsort.rs, examples/test_dir_escape/examples/test_dir_escape.rs, examples/validator/examples/validator.rs, sqllogictest-bin/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs, tests/harness.rs
Signed-off-by: Yongting You <2010youy01@gmail.com>
Close [#117 ](https://github.com/risinglightdb/sqllogictest-rs/issues/117)
This PR adds multiple blob files CLI support (as #117 suggested)
The following CLI inputs have been tested locally
1. One unquoted glob
```
> ./target/debug/sqllogictest ./**/*.slt 
...(tests runned)
```
2. No input file
```
> ./target/debug/sqllogictest
error: The following required arguments were not provided:
<FILES>...
USAGE:
sqllogictest [OPTIONS] <FILES>...
For more information try --help
```
3. Multiple globs
```
> ./target/debug/sqllogictest ./examples/basic/*.slt "./examples/condition/*.slt" ./examples/rowsort/rowsort.slt
...(tests runned)
```
=> CLI: support multiple files as input

Cargo.lock, README.md, examples/basic/examples/basic.rs, examples/condition/examples/condition.rs, examples/custom_type/Cargo.toml, examples/custom_type/custom_type.slt, examples/custom_type/examples/custom_type.rs, examples/file_level_sort_mode/examples/file_level_sort_mode.rs, examples/include/examples/include.rs, examples/rowsort/examples/rowsort.rs, examples/test_dir_escape/examples/test_dir_escape.rs, examples/validator/examples/validator.rs, sqllogictest-bin/src/engines.rs, sqllogictest-bin/src/lib.rs, sqllogictest-engines/src/external.rs, sqllogictest-engines/src/postgres/extended.rs, sqllogictest-engines/src/postgres/simple.rs, sqllogictest/src/column_type.rs, sqllogictest/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs, tests/harness.rs
Signed-off-by: Yevhenii Melnyk <melnyk.yevhenii@gmail.com>
Partially closes #36.
I'd like to introduce column type verification for Datafusion https://github.com/apache/arrow-datafusion/issues/4499.
In order to let downstream users of `sqllogictest-rs` to define custom column types and validation strategies, I suggest introducing a pluggable column type. This way different `AsynDB` and `DB` implementations would be able to define column types beyond the original 'T','I','R' [like CocroachDB does](https://github.com/cockroachdb/cockroach/blob/899c9112188c22ec140adbeb0cf7d5761da3827d/pkg/sql/logictest/logic.go#L282-L289), or shrinking the set of columns to only having `I` [like DuckDB suggests](https://duckdb.org/dev/sqllogictest/result_verification).
This pr introduces an interface …
=> feat: Customizable column types and validators

examples/custom_type/custom_type.slt, examples/custom_type/examples/custom_type.rs, sqllogictest-bin/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
This pr introduced a way to use custom column types https://github.com/risinglightdb/sqllogictest-rs/pull/160.
But the completion code kept ignoring the types.
This pr updates the implementation to complete column types the same way results are completed.
=> Customizable types follow up: complete types in update_test_file

.github/workflows/ci.yml
waiting for upstream fix this https://github.com/obi1kenobi/cargo-semver-checks/issues/370
=> fix(ci): lock check-semver to 0.17

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/basic/basic.slt, examples/basic/examples/basic.rs, sqllogictest/src/runner.rs
This pr updates the autocompletion logic for the regex special characters.
Currently, the issues lead to cryptic errors like
```
Error: query is expected to fail with error:
DataFusion error: Error during planning: arrow_cast requires its second argument to be a constant string, got Int64(43)
but got error:
DataFusion error: Error during planning: arrow_cast requires its second argument to be a constant string, got Int64(43)
[SQL] SELECT arrow_cast('1', 43)
at tests/sqllogictests/test_files/arrow_typeof.slt:98
```
The problem is that the autocompletion mode added the plain brachets `()` in the example above. And it should've escaped the brackets with `\(\)`. Otherwise, they are treated as a regex group.
For more details about the issue, please, see …
=> Escape regex special characters in the completion mode

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/bin/sqllogictest.rs, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
Users can now add `--label` options to skip commands. resolve #177 
For example:
```
sqllogictest --label risingwave ... xxx.slt
```
```slt
skipif risingwave
query I
select some_features_not_supported_yet();
```
This PR also bumps version to v0.14.0.
=> feat: add label for `skipif` and `onlyif` conditions

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/basic/examples/basic.rs, examples/condition/examples/condition.rs, examples/connection/Cargo.toml, examples/connection/connection.slt, examples/connection/examples/connection.rs, examples/custom_type/examples/custom_type.rs, examples/file_level_sort_mode/examples/file_level_sort_mode.rs, examples/include/examples/include.rs, examples/rowsort/examples/rowsort.rs, examples/test_dir_escape/examples/test_dir_escape.rs, examples/validator/examples/validator.rs, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/engines.rs, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest/src/connection.rs, sqllogictest/src/harness.rs, sqllogictest/src/lib.rs, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
[DuckDB's sqllogictest implementation](https://duckdb.org/dev/sqllogictest/multiple_connections) provides the ability for establishing multiple connections in an `slt` file and specify which to use for each query or statement, which is helpful for testing database transactions.
This PR implements a similar feature, except that we will use a line `connection <name>` instead of the DuckDB's syntax since it is already utilized by our error matching feature.
This is a breaking change to the interfaces of the library crate (like `Runner::new`), so maybe we need to bump the minor version under `0`.
=> feat: support multiple connections (sessions) in a single test file

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/main.rs
... because it's totally noise for users
=> fix(bin): do not print stack backtrace on error

.github/workflows/release-notes.py, .github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/main.rs
revert #189. Error context is printed only for `{:?}`.
For backtrace, according to anyhow's doc,
> If using the nightly channel, or stable with features = ["backtrace"], a backtrace is captured and printed with the error if the underlying error type does not already provide its own. In order to see backtraces, they must be enabled through the environment variables described in std::backtrace
So we can either: ship pre-built binary which is built by stable or unset `RUST_BACKTRACE` to hide backtrace.
---
Also update release workflow close https://github.com/risinglightdb/sqllogictest-rs/issues/182
=> fix error context display & update release workflow

sqllogictest-bin/src/main.rs
For slt file structure like:
```
- a
- foo.slt
- b
- foo.slt
```
sqllogictest-bin will report `duplicated file name found` before this PR. See https://buildkite.com/risingwavelabs/pull-request/builds/31646#018a92e8-75f8-48f6-8777-cf2ecb592775
=> fix: fix parallel testing db name duplication

sqllogictest/src/runner.rs
Complement for https://github.com/risinglightdb/sqllogictest-rs/pull/194.
=> fix(runner): fix parallel testing db name duplication

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-engines/Cargo.toml, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs
Resolve https://github.com/risinglightdb/sqllogictest-rs/pull/200#pullrequestreview-1720245593.
Hide the whitespaces for better review experiences. :)
=> refactor: use sum type for expects in records

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs, sqllogictest/src/runner.rs
Signed-off-by: xxchan <xxchan22f@gmail.com>
=> feat(bin): add random suffix to the temporary databases

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml
Previous we have logs like this
=> feat(bin): hide `INFO` level log by default

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest/src/connection.rs, sqllogictest/src/runner.rs, sqllogictest/src/substitution.rs
In `Runner`, we create a new runner for each parallelism without reusing `self.conn`, which is not good. What's worse is that we don't inherit other fields from `self`, resulting in `add_label` not taking effect when running in parallel.
=> fix: inherit configuration in `run_parallel`

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-engines/Cargo.toml, sqllogictest/src/runner.rs
`RecordOutput` is now returned by `Runner::run` (or `Runner::run_async`). This allows users to access the output of each record, or check whether the record is skipped.
=> refactor: return record output in run

CHANGELOG.md, sqllogictest/src/runner.rs, sqllogictest/src/substitution.rs, tests/system_command/system_command.slt
fix https://github.com/risinglightdb/sqllogictest-rs/issues/218
=> feat: don't subst env vars for `system`

CHANGELOG.md, README.md, sqllogictest/src/runner.rs, tests/system_command/system_command.slt
close #217
- no strong motivation to make it configurable yet
- bash's extensions are useful for scripting: arrays, loops, heredoc, etc.
- When the machine's `sh` is actually `bash`, using `sh` to execute will succeed without warnings. This caused a lot of trouble for me (i.e., why it works locally, but not in CI?)
=> feat: change `sh` to `bash`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/engines.rs, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest-engines/src/lib.rs, sqllogictest-engines/src/mysql.rs
=> feat: add mysql engine to cli

.github/workflows/ci.yml, Cargo.lock, sqllogictest-engines/src/mysql.rs, sqllogictest-engines/src/postgres/postgres_simple_test.slt, sqllogictest-engines/src/postgres/simple.rs, sqllogictest/src/lib.rs, sqllogictest/src/runner.rs
related: https://github.com/sfackler/rust-postgres/commit/6cd4652bad6ac8474235c23d0e4e96cc4aa4d8db, https://github.com/sfackler/rust-postgres/pull/1144, the upstream commit breaks semver (?)
close https://github.com/risinglightdb/sqllogictest-rs/issues/232
* add support for the row description message. in the simple engine, we just ignore it.
* add a test case with Postgres simple wire protocol
* also bump dependencies
=> fix(engines): support simple row desc message

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs, tests/custom_type/custom_type.rs, tests/slt/rowsort.slt, tests/slt/valuesort.slt, tests/validator/validator.rs
I've adding some functionality to support running the sqlite test suite against another database and this PR is the initial part of that work. This PR adds:
- valuesort from PR #123 
- a new control `resultmode` of either `valuewise` or `rowwise` (defaulting to the latter)
- a new value normalizer to allow for different value normalization for different files
The last point is a breaking API change so I took the liberty to rev the version #. If that isn't desired feel free to revert that portion of this PR.
With this PR I am able to run a slightly cleansed sqlite test suite using the Datafusion sqllogictest harness.
=> Add valuesort, new control result mode and value normalizer

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, sqllogictest-bin/Cargo.toml, sqllogictest-engines/Cargo.toml, sqllogictest/src/parser.rs, sqllogictest/src/runner.rs, tests/retry/query_retry.slt, tests/retry/statement_retry.slt
Resolves https://github.com/risinglightdb/sqllogictest-rs/issues/238.
Also removed `label` from `QueryExpect::Results` because it's never used.
=> feat: support retry

.github/workflows/release.yml
generate binaries: https://github.com/usamoi/sqllogictest-rs/releases/tag/v0.0.0
=> build aarch64-linux-musl binary for releases

README.md, sqllogictest/src/parser.rs, tests/retry/query_retry.slt, tests/retry/statement_retry.slt
Previous PR #239 doesn't support `retry` for error query or statement. This is because any tokens after the `[statement|query] error` are treated as error message regex.
However, we found this case is useful. https://github.com/risinglightdb/sqllogictest-rs/pull/239#discussion_r1901548064
This PR adds support for `[statement|query] error` with multiline message. As a compromise, the single-line syntax `[statement|query] error <error message regex...>` is not supported.
=> feat: support retry for `[statement|query] error`

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/main.rs
=> feat(bin): support --fail-fast

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs
Improvement to https://github.com/risinglightdb/sqllogictest-rs/pull/246.
=> feat(bin): abort connections before dropping temp databases in parallel run

Cargo.lock, sqllogictest/Cargo.toml, sqllogictest/src/runner.rs
We encountered an error while running sqllogictest in datafusion.
https://github.com/apache/datafusion/issues/12752
https://github.com/apache/datafusion/pull/14254
This happens when multiple .slt file include from a single parent file while running on multiple threads.
This result in creation of multiple temp file(for parent file) and subsequent failure as these temp files are removed by one thread and then other tries to remove/access it too.
A simple solution is to add a random string to `outfilename` as done in this PR.
=> Add random string in path generation

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/main.rs
https://buildkite.com/risingwavelabs/pull-request/builds/66205
=> feat(bin): detect connection refused error and exit early

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/engines.rs, sqllogictest-bin/src/main.rs, sqllogictest-engines/Cargo.toml, sqllogictest-engines/src/external.rs, sqllogictest-engines/src/mysql.rs, sqllogictest-engines/src/postgres.rs, sqllogictest-engines/src/postgres/extended.rs, sqllogictest-engines/src/postgres/simple.rs, sqllogictest/src/connection.rs, sqllogictest/src/harness.rs, sqllogictest/src/runner.rs
Add `shutdown` method to `AsyncDB`. Implement it for all engines. Adopt it in binary.
Previously we have a `Drop` impl for `Postgres` which directly aborts the background connection. This is not good as there's no chance for the pgwire protocol to gracefully shutdown itself. As a result, we see `failed to read message: unexpected end of file` every time a test case (file) completes in the server side.
Simply removing this `Drop` impl and letting the connection run to completion in the background resolves this issue. However, let's get one step further and propose a general design to all kinds of database engines by manually specifying and calling the `shutdown` method.
----
=> feat: add `shutdown` method to `AsyncDB` `DB` and `Runner`

CHANGELOG.md, sqllogictest-bin/src/main.rs, sqllogictest/src/lib.rs, sqllogictest/src/runner.rs, sqllogictest/src/substitution.rs, tests/substitution/basic.slt, tests/substitution/substitution.rs
- runner: Add `Runner::set_var` method to add runner-local variables for substitution.
- bin: Add `__DATABASE__` variable for accessing database name from SLT files.
=> feat: support local variable substitution, add `__DATABASE__` variable for bin

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml
So that we don't need to both push tags and manually run `cargo publish`. And anyone with push tag permission can publish now. 
cc @risinglightdb/crates-io
=> ci: cargo publish on tag

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-engines/src/external.rs
it seems that we can not pass EOF to child process's stdin by `shutdown()`.
as the doc from tokio described, `shutdown()` will fire a `shutdown(Write)` syscall to the socket. but this syscall does not works for file descriptors other than socket.
```
/// Shuts down the output stream, ensuring that the value can be dropped
/// cleanly.
///
/// Equivalent to:
///
/// ```ignore
/// async fn shutdown(&mut self) -> io::Result<()>;
/// ```
///
/// Similar to [`flush`], all intermediately buffered is written to the
/// underlying stream. Once the operation completes, the caller should
/// no longer attempt to write to the stream. For example, the
/// `TcpStream` implementation will issue a `shutdown(Write)` sys call.
///
/// [`flush`]: fn@crate::io::AsyncWriteExt::flush
```
to real `close()` the …
=> fix(external): close stdin properly in shutdown()

CHANGELOG.md, sqllogictest-bin/Cargo.toml, sqllogictest-bin/src/main.rs
Significantly refactor the `bin` impl and enhance the cancellation handling:
- Extract `connect_and_run_test_file` to be shared by both `run_parallel` and `run_serial`.
- Extract the common logic for converting a test result into a JUnit test case in `run_parallel` and `run_serial`.
- Introduce `CancellationToken` to unify all kinds of cancellation, including `--fail-fast` (#246) and early-exit on "connection refused" (#248).
- Support `Ctrl-C` as an origin of cancellation.
- In parallel mode: when cancellation is triggered, we will first await all running cases to be cancelled (disconnecting their sessions), then skip the ones that haven't started.
- Also output lines for `[CANCELLED]` or `[SKIPPED]` test cases. This can be very useful to …
=> feat(bin): handle cancellation & early-exit & ctrl-c gracefully

CHANGELOG.md, sqllogictest-engines/src/postgres.rs
Otherwise we have to wait for the ongoing query to be finished before `shutdown` can return, which doesn't seem friendly when handling cancellation from the user.
=> feat(engines): cancel ongoing query when shutting down postgres connection

CHANGELOG.md, Cargo.lock, Cargo.toml, sqllogictest-bin/src/main.rs
...so that upon cancellation, we get more prompt results from ongoing tests.
=> feat(bin): flush output to stdout before db conn shutdown

sqllogictest-bin/src/main.rs
Signed-off-by: Cheng Chen <ccqmpux@gmail.com>
Without the fix, override mode omits the final newline, resulting in output like:
```
vscode ➜ /workspaces/pg_mooncake (rust) $ sqllogictest tests/sanity.slt --override
tests/sanity.slt                                             .. [OK] in 11 msvscode ➜ /workspaces/pg_mooncake (rust ✗) $ 
```
In contrast, non-override mode prints the newline correctly:
```
vscode ➜ /workspaces/pg_mooncake (rust ✗) $ sqllogictest tests/sanity.slt
tests/sanity.slt                                             .. [OK] in 5 ms
vscode ➜ /workspaces/pg_mooncake (rust ✗) $ 
```
=> fix(bin): add missing newline in override mode
